# Generated by Django 2.1.1 on 2018-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0002_auto_20181013_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='left_to_pay',
            field=models.IntegerField(default=0),
        ),
    ]
