# Generated by Django 2.1.1 on 2018-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0004_partoflilexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
