# Generated by Django 2.1.1 on 2018-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0005_partofexpense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='order_number',
            field=models.IntegerField(default=-1),
        ),
    ]
