# Generated by Django 2.1.1 on 2018-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0007_auto_20181023_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
