# Generated by Django 2.1.1 on 2018-10-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0008_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='partner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exp_names', to='ulesys.Partner'),
        ),
    ]
