# Generated by Django 2.1.1 on 2018-10-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0010_auto_20181026_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partofexpense',
            name='partner',
        ),
    ]
