# Generated by Django 2.1.1 on 2018-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0012_partofexpense_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partofincome',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partoflilexpense',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wholeexpense',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wholeincome',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
    ]
