# Generated by Django 2.1.1 on 2018-11-10 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0014_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tour_starts',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
