# Generated by Django 2.1.1 on 2018-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0016_auto_20181110_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofexpense',
            name='pay_days',
            field=models.CharField(default='', max_length=900),
        ),
    ]
