# Generated by Django 2.1.1 on 2018-11-17 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0017_partofexpense_pay_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_days', to='ulesys.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='getpayedday',
            name='order',
        ),
        migrations.RemoveField(
            model_name='partofexpense',
            name='pay_days',
        ),
        migrations.DeleteModel(
            name='GetPayedDay',
        ),
        migrations.AddField(
            model_name='payday',
            name='part_of_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_days', to='ulesys.PartOfExpense'),
        ),
    ]
