# Generated by Django 2.1.1 on 2018-12-12 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0019_auto_20181124_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPayedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_payed_days', to='ulesys.Order')),
            ],
        ),
    ]
