# Generated by Django 2.1.1 on 2018-12-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0024_auto_20181225_0623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
