# Generated by Django 2.1.1 on 2018-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulesys', '0025_delete_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_base',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
